name: iOS

on:
  workflow_dispatch:
#  pull_request:
#  push:
#    tags:
#      - 'v*'

jobs:
  e2e:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        id: ios-cache
        with:
          path: |
            example/ios/build/*
            example/ios/Pods/*
          key: ios
      - name: Set up Node
        run: |
          npm install -g detox-cli
          npm install -g yarn
      - name: Install Detox
        run: |
          brew tap wix/brew
          brew install applesimutils
      - run: yarn
      - run: yarn example build:ios
      - run: yarn example start &
        timeout-minutes: 20
      - run: yarn example test:ios
